config/routes.rb
Rails.application.routes.draw do
  get 'home/index' 

  resources :articles do
    resources :comments
  end
  
  get 'articles' => 'articles#index'
  get 'articles/:id' => 'articles#show'

  get 'news/:id-:title' => 'articles#show', as: :read

   root 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
						length: { minimum: 5}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	http_basic_authenticate_with name: "aris", password: "aris", except: [:index, :show]

	def index
		#@articles = Article.all
		@articles = Article.paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@article = Article.new
	end

	def show
		@article = Article.find(params[:id])
	end

	def create
		#render plain: params[:article].inspect
		@article = Article.new(article_params)
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'	
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end

	private
		def article_params
			params.require(:article).permit(:title, :text)		
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	http_basic_authenticate_with name: "aris", password: "aris", only: :destroy

	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end

	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@articles = Article.paginate(:page => params[:page], :per_page => 10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
	<% if @article.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
		<ul>
			<% @article.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<p>
		<%= f.label :title %> <br>
		<%= f.text_field :title %> 
	</p>
	<p>
		<%= f.label :text %> <br>
		<%= f.text_area :text %> 
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>
<%# form_for :article, url: article_path(@article), method: :patch do |f| %>
<%= render 'form' %>

<p><%= link_to 'Go Back', articles_path %></p>

app/views/articles/index.html.erb
<p><%= link_to 'New article', new_article_path %></p>
<table>
	<tr>
		<th>No</th>
		<th>Title</th>
		<th>Text</th>
		<th colspan="3">Action</th>
	</tr>
	<% @articles.each_with_index do |article, i| %>
	<% i+=1 %>
	<tr>
		<td><%= i %></td>
		<td><%= article.title %></td>
		<td><%= article.text %></td>
		<td><%= link_to 'Show', article_path(article) %></td>
		<td><%= link_to 'Edit', edit_article_path(article) %></td>
		<td><%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?'} %></td>
	</tr>
	<% end %>
</table>

<%= will_paginate @articles %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%# form_for :article, url: articles_path do |f| %>
<%= render 'form' %>

<p><%= link_to 'Go Back', articles_path %></p>

app/views/articles/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @article.title %>
</p>
<p>
	<strong>Text:</strong>
	<%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>
  

<p><%= link_to 'Go Back', articles_path %> | <%= link_to 'Edit', edit_article_path(@article) %></p>

app/views/comments/_comment.html.erb
<p>
	<strong>Commenter :</strong>
	<%= comment.commenter %>
</p>
<p>
	<strong>Comment :</strong>
	<%= comment.body %>
</p>

<p>
	<%= link_to 'Delete Comment', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
	<p>
		<%= f.label :commenter %>
		<%= f.text_field :commenter %>
	</p>
	<p>
		<%= f.label :body %>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit %>
	</p>
		
<% end %>

app/views/home/index.html.erb
<div class="container">

  <!-- Masthead
  ================================================== -->
  <header>
    
<%= render 'layouts/toppanel' %>
<%= render 'layouts/navbar' %>
    


  </header>    



<%= render 'layouts/blog' %>
<%= render 'layouts/footer' %>
  
  </div><!-- /container -->



    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  <%= javascript_include_tag 'jquery.easing.1.3', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'superfish', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.tweet', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jflickrfeed.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.flexslider-min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.fitvid', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.prettyPhoto', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.preloader', 'data-turbolinks-track' => true %>
  
    <!-- Support CSS3 Media Queries for IE 6-8 -->
  <%= javascript_include_tag 'respond.min', 'data-turbolinks-track' => true %>

  <script>
    jQuery.noConflict()(function($){
      $('.blog-carousel').flexslider({
          animation: "slide",
            controlNav: false,
          animationLoop: false,
          slideshow: false,
          touch: true,
          itemWidth: 160,
          itemMargin: 5,
          asNavFor: '.blog-slider'
        });
   
      $('.blog-slider').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: false,
        slideshow: false,
        touch: true,
        sync: ".blog-carousel"
      });
    });
  </script>

  <%= javascript_include_tag 'custom', 'data-turbolinks-track' => true %>

	<!-- For Images Preloading -->
	<script type="text/javascript">var runFancy = true;</script>
	
    <!--[if IE]>
    <script type="text/javascript">
      runFancy = false;
    </script>
    <![endif]-->
    
    <script type="text/javascript">
      if (runFancy) {
        jQuery.noConflict()(function($){
          $(".view").preloader();
          });
        };
	</script>

app/views/layouts/_blog.html.erb
<!-- Blog
  ================================================== -->
    <div class="row entry-blog">
	  <div class="span9">
	  
    	<!-- START POST #4 SLIDESHOW -->
	    <div class="row entry-post">

		<!-- Popular Posts -->
		<div class="span3">
		    <div class="widget well">
		      <h5>Berita Terbaru</h5>
			  <ul class="popular-posts">
			    <% @articles.each do |article| %>
			    	<li>
				    	<a href="#"><img src="<%= asset_path("img/blog/widgets/img01-40x40.jpg") %>" alt="" /></a>
			    		<%= link_to article.title, read_url(article, article.title.parameterize) %>
			    		<span class="date"><%= article.created_at.strftime("%B %e, %Y") %></span>
			    	</li>
			    <% end %>

			  </ul>
		    </div><!-- widget -->
	    </div>
	  
	      <!-- POST FORMAT - SLIDESHOW -->
	      <div class="span6">
	        <div class="row">
	          <div class="span6 format-slideshow">
	            <div class="thumb-post view">
				  <div class="blog-slider flexslider clearfix">
        			<ul class="slides">
          			  <li>
            			<img src="<%= asset_path("img/blog/img03.jpg") %>" alt="" />
          			  </li>
          			  <li>
            			<img src="<%= asset_path("img/blog/img02.jpg") %>" alt="" />
          			  </li>
          			  <li>
            			<img src="<%= asset_path("img/blog/img01.jpg") %>" alt="" />
          			  </li>
          			  <li>
            			<img src="<%= asset_path("img/blog/img05.jpg") %>" alt="" />
          			  </li>
    				  <li>
      				    <img src="<%= asset_path("img/blog/img04.jpg") %>" alt="" />
    				  </li>
    				  <li>
      				    <img src="<%= asset_path("img/blog/img06.jpg") %>" alt="" />
    				  </li>
        			</ul>
      			  </div><!-- blog-slider -->
	              <div class="post-date-meta">
                	<span class="month">July</span>
              		<span class="date">02</span>
            	  </div><!-- post-date-meta -->
	        	</div><!-- thumb-post -->
				<div class="blog-carousel flexslider">
				  <ul class="slides">
    				<li>
      				  <img src="<%= asset_path("img/blog/img03.jpg") %>" alt="" />
    				</li>
    				<li>
      				  <img src="<%= asset_path("img/blog/img02.jpg") %>" alt="" />
    				</li>
    				<li>
      				  <img src="<%= asset_path("img/blog/img01.jpg") %>" alt="" />
    				</li>
    				<li>
      				  <img src="<%= asset_path("img/blog/img05.jpg") %>" alt="" />
    				</li>
    				<li>
      				  <img src="<%= asset_path("img/blog/img04.jpg") %>" alt="" />
    				</li>
    				<li>
      				  <img src="<%= asset_path("img/blog/img06.jpg") %>" alt="" />
    				</li>
				  </ul>
				</div><!-- carousel -->
	        	<div class="entry-text">
	        	  <h3><a href="blog-post.html">Slideshow Post Format</a></h3>
	        	  <p>Vestibulum vitae tellus a turpis accumsan egestas et non nulla. Phasellus lacinia semper aliquam. Proin ipsum enim, fringilla quis vulputate ut, auctor vestibulum magna. Phasellus non eros vel dui ornare pulvinar. Proin eget magna et orci pellentesque rutrum et at turpis. Nam ut turpis eget odio varius rhoncus.</p>
	        	  <a class="btn" href="blog-post.html">Read more</a>
	        	</div><!-- entry-text -->
	          </div><!-- span6 -->
	        </div><!-- row -->
	      </div><!-- span6 -->
	    </div><!-- row -->
	    
	    <!-- DIVIDER -->
      	<div class="row margin40">
      	  <div class="span3"><div class="border-5-1"></div></div>
      	  <div class="span6"><div class="border-5-1 hide-border"></div></div>
    	</div><!-- row -->
  	 	<!-- END POST #4 -->


		<!-- ============================================================================================= -->


		<!-- ============================================================================================= -->


    	<!-- START POST #6 QUOTE -->    	
	    <div class="row entry-post">
  	      <div class="span3">
	        <div class="entry-meta clearfix">
	          <span><strong><i class="icon-user"></i> Author:</strong> <a href="#">ZERGE</a></span>
	          <span><strong><i class="icon-comment"></i> Comments:</strong> <a href="#">1</a></span>
	          <span><strong><i class="icon-list-alt"></i> Category:</strong> <a href="#">Quote</a></span>	      
	          <span><strong><i class="icon-tags"></i> Tags:</strong></span>
	          <ul class="tags clearfix">
      	        <li><a href="#">quote</a></li>
	            <li><a href="#">copyright</a></li>
		      </ul>
	        </div><!-- entry-meta -->
	      </div><!-- span3 -->
	  
	      <!-- POST FORMAT - QUOTE -->
	      <div class="span6">
	        <div class="row">
	          <div class="span6 format-video">
	        	<div class="entry-text">
				  <h3><a href="blog-post.html">Quote</a></h3>
	        	  <blockquote cite="http://amour-discipline.org/zine/how-the-copyright-industry-drives-a-big-brother-dystopia/">
	        	    <p>All too often I hear that the copyright industry doesn’t understand the Internet, doesn’t understand the net generation, doesn’t understand how technology has changed.</p>
  					<small>Rick Falkvinge</small>
	        	  </blockquote>
	        	</div><!-- entry-text -->
	          </div><!-- span6 -->
	        </div><!-- row -->
	      </div><!-- span6 -->
	    </div><!-- row -->
	    
	    <!-- DIVIDER -->
      	<div class="row margin40">
      	  <div class="span3"><div class="border-5-1"></div></div>
      	  <div class="span6"><div class="border-5-1 hide-border"></div></div>
    	</div><!-- row -->
  	 	<!-- END POST #6 -->

	    <!-- PAGINATION  -->
       	<div class="row margin40">
      	  <div class="span3"><p></p></div>
      	  <div class="span6">
      	    <div class="pagination">
              <ul>
                <li><a href="#"></a></li>
            	<li class="active"><a href="#">1</a></li>
            	<li><a href="#">2</a></li>
            	<li><a href="#">3</a></li>
            	<li><a href="#">4</a></li>
            	<li class="disabled"><a href="#">...</a></li>
            	<li><a href="#">10</a></li>
            	<li><a href="#"></a></li>
          	  </ul>
        	</div><!-- pagination -->
      	  </div><!-- span6 -->
    	</div><!-- row -->



	  </div><!-- span9 -->


  	  <!-- ============================================================================================= -->


	  <!-- SIDEBAR -->
      <div class="span3 sidebar">
        <div class="widget well">
          <form method="get" id="searchform" action="http://html.color-theme.com/linkup">
            <div class="input-prepend">
              <span class="add-on"><i class="icon-search"></i></span><input class="search-box" id="search-box" type="text" name="name" value="To search type and hit enter" onFocus="if(this.value=='To search type and hit enter')this.value='';" onBlur="if(this.value=='')this.value='To search type and hit enter';">
        	</div>
          </form>
        </div><!-- widget -->

	    <!-- About -->
        <div class="widget well">
          <h5>About</h5>
          <p class="last">Claystone is <span class="label">Responsive</span> HTML Template, makes perfect for a variety of purposes, although focused towards Photographers and those using Portfolios to display their past and present work collections.</p>
		</div><!-- .widget -->

		<!-- Categories -->
        <div class="widget widget-list well">
          <h5>Categories</h5>
          <ul class="nav nav-list">
          <li><a href="#"><i class="icon-list-alt"></i> Home</a></li>
          <li><a href="#"><i class="icon-list-alt"></i> Library</a></li>
          <li><a href="#"><i class="icon-list-alt"></i> Applications</a></li>
          <li><a href="#"><i class="icon-list-alt"></i> Misc</a></li>
        </ul>
        </div><!-- widget -->

		<!-- Popular Posts -->
	    <div class="widget well">
	      <h5>Popular Posts</h5>
		  <ul class="popular-posts">
		    <li>
		      <a href="#"><img src="<%= asset_path("img/blog/widgets/img01-40x40.jpg") %>" alt="" /></a>
		      <a href="#">Domino Theory</a>
		      <span class="date">June 24, 2012</span>
		    </li>
		    <li>
		      <a href="#"><img src="<%= asset_path("img/blog/widgets/img02-40x40.jpg") %>" alt="" /></a>
		      <a href="#">Crossing Paths</a>
		      <span class="date">June 22, 2012</span>
		    </li>
		    <li>
		      <a href="#"><img src="<%= asset_path("img/blog/widgets/img03-40x40.jpg") %>" alt="" /></a>
		      <a href="#">Corporate Equality Index</a>
		      <span class="date">May 09, 2012</span>
		    </li>
		  </ul>
	    </div><!-- widget -->
	    
	    <!-- Popular tags -->
        <div class="widget well">
          <h5>Popular tags</h5>
		  <ul class="tags clearfix">
      	    <li><a href="#">quote</a></li>
	        <li><a href="#">copyright</a></li>
	        <li><a href="#">brand</a></li>
	        <li><a href="#">tag</a></li>
	        <li><a href="#">design</a></li>
	        <li><a href="#">graphics</a></li>
	        <li><a href="#">battle</a></li>
	        <li><a href="#">envato</a></li>
		  </ul>
          <small><a href="#">View all tags</a></small>
		</div><!-- .widget -->
		
	
      </div><!-- span3 -->
	</div><!-- row -->

app/views/layouts/_footer.html.erb
<!-- Footer
================================================== -->
  <footer class="footer row">
    <div class="span3">
      <div class="logo-footer widget">
        <h5>Contact Info</h5>
		<ul id="contact-info" class="clearfix">
		  <li><i class="icon-map-marker icon-white"></i><address>12345 / Some Street, Portland, USA</address></li>
		  <li><i class="icon-user icon-white"></i>phone: +1 (44)  123-45-67</li>
		  <li><i class="icon-headphones icon-white"></i><a href="skype:echo123?call">Skype Me</a></li>
		  <li><i class="icon-envelope icon-white"></i><a href="mailto:support@color-theme.com">support@color-theme.com</a></li>
		</ul>
      </div><!-- logo-footer -->
    </div><!-- span3 -->
    
    <div class="span9 footer-widgets clearfix">
	  <div class="widget">
	    <h5>Popular Posts</h5>
		<ul class="popular-posts">
		  <li>
		    <a href="#"><img src="<%= asset_path("img/blog/widgets/img01-40x40.jpg") %>" alt="" /></a>
		    <a href="#">Domino Theory</a>
		    <span class="date">June 24, 2012</span>
		  </li>
		  <li>
		    <a href="#"><img src="<%= asset_path("img/blog/widgets/img02-40x40.jpg") %>" alt="" /></a>
		    <a href="#">Crossing Paths</a>
		    <span class="date">June 22, 2012</span>
		  </li>
		  <li>
		    <a href="#"><img src="<%= asset_path("img/blog/widgets/img03-40x40.jpg") %>" alt="" /></a>
		    <a href="#">Corporate Equality Index</a>
		    <span class="date">May 09, 2012</span>
		  </li>
		</ul>
	  </div><!-- .widget -->

	  <div class="widget">
	    <h5>Latest Posts</h5>
		<ul class="latest-posts">
		  <li>
		    <a href="#"><img src="<%= asset_path("img/blog/widgets/img04-40x40.jpg") %>" alt="" /></a>
		    <a href="#">The Peace Corps</a>
		    <span class="date">Jule 02, 2012</span>		  
		  </li>
		  <li>
		    <a href="#"><img src="<%= asset_path("img/blog/widgets/img01-40x40.jpg") %>" alt="" /></a>
		    <a href="#">Domino Theory</a>
		    <span class="date">June 24, 2012</span>
		  </li>
		  <li>
		    <a href="#"><img src="<%= asset_path("img/blog/widgets/img05-40x40.jpg") %>" alt="" /></a>
		    <a href="#">Flickr Eggs</a>
		    <span class="date">May 14, 2012</span>
		  </li>
		</ul>
	  </div><!-- .widget -->

	 <!--  <div class="widget">
	    <h5>Flickr Photos</h5>
	    <ul class="flickr thumbs"></ul>
	  </div><!-- .widget --> 
	  
    </div><!-- footer-widgets -->
  </footer>

  <div id="bottom-panel" class="clearfix">
  <span class="site-name">Claystone — Responsive HTML Template</span>
  <span>Copyright &copy; 2012. Designed by <a href="http://themeforest.net/user/ZERGE?ref=zerge">ZERGE</a> for <a href="http://themeforest.net/user/ZERGE/portfolio?ref=zerge">Themeforest</a>.</span></div>

app/views/layouts/_navbar.html.erb
    <!-- Navbar
    ================================================== -->
    <div class="row">
      <div class="span3 logo">
        <a href="."><img src="<%= asset_path("img/logo.png") %>" alt="" /></a>
      </div><!-- logo -->
      <div class="span9 navigation">
        <div id="menu" class="fix-fish-menu clearfix">
          <ul id="nav" class="sf-menu">
            <li><a href="index.html">Home</a>
              <ul>
                <li><a href="index-flex.html">Home + Flex Slider</a></li>
              </ul>
            </li>
            <li class="active"><a href="blog.html">Blog</a>
              <ul>
                <li><a href="blog.html">Blog</a></li>
                <li><a href="blog-post.html">Blog Post + Image</a></li>
                <li><a href="blog-post-video.html">Blog Post + Video</a></li>                
              </ul>
            </li>
			<li> <a href="#">Portfolio</a>
			  <ul>
				<li><a href="portfolio-3.html">3 Columns <span class="sf-sub-indicator"></span></a>
				  <ul>
				    <li><a href="portfolio-3.html">3 Columns + Horizontal</a></li>
				    <li><a href="portfolio-vertical-3.html">3 Columns + Vertical</a></li>
				    <li><a href="portfolio-description-3.html">3 Columns + Description</a></li>
				    <li><a href="portfolio-big-3.html">3 Big Columns</a></li>
				  </ul>
				</li>
				<li><a href="">4 Columns <span class="sf-sub-indicator"></span></a>
				  <ul>
					<li><a href="portfolio-4.html">4 Columns + Horizontal</a></li>
				    <li><a href="portfolio-description-4.html">4 Columns + Description</a></li>
					<li><a href="portfolio-vertical-4.html">4 Columns + Vertical</a></li>
				  </ul>
				</li>
				<li><a href="#">Portfolio Item <span class="sf-sub-indicator"></span></a>
				  <ul>
				  	<li><a href="item.html">Standard</a></li>
					<li><a href="item-slideshow.html">Slideshow</a></li>
					<li><a href="item-video.html">Video</a></li>
				  </ul>
				</li>
				<li><a href="gallery.html">Gallery</a></li>
			  </ul>
			</li>
			<li> <a href="typography.html">Typography</a></li>
			<li> <a href="shortcodes.html">Shortcodes</a></li>
			<li> <a href="#">Pages</a>
			  <ul>
			    <li><a href="left-content.html">Left + Content</a></li>
				<li><a href="content-right.html">Content + Right</a></li>
				<li><a href="full-width.html">Full Width Page</a></li>
				<li><a href="#">Submenu <span class="sf-sub-indicator"></span></a>
			      <ul>
					<li><a href="#">Item #1</a></li>
					<li><a href="#">Item #2</a></li>
				  </ul>
				</li>
			  </ul>
			</li>
		 	<li><a href="contacts.html">Contacts</a></li>
            <li><a href="http://themeforest.net/item/claystone-responsive-html-template/2746744?ref=zerge"><i class="icon-shopping-cart icon-white"></i>Purchase</a></li>
          </ul><!-- end #nav  -->
        </div><!-- end #menu  -->
      </div><!-- navigation -->
    </div><!-- row -->

app/views/layouts/_toppanel.html.erb
    <!-- Top Panel
    ================================================== -->
    <div id="top-panel">
      <div class="login-box">
        <form>
		  <div class="input-prepend">
            <span class="add-on"><i class="icon-user"></i></span><input class="span2" id="username" type="text" name="username" placeholder="User Name">
          </div>
		  <div class="input-prepend">
            <span class="add-on"><i class="icon-lock"></i></span><input class="span2" id="userpassword" type="password" name="userpassword" placeholder="Password">
          </div>
          <label class="checkbox">
    		<input type="checkbox"> Remember me
  		  </label>
          <button type="submit" class="btn">Sign in</button>
        </form>
      </div><!-- login-box -->
      <div class="login-button toggle">
        <a href="#">Sign in</a>
      </div><!-- login-button -->
    </div><!-- top-panel -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>News</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  	<meta charset="utf-8">
	<meta name="author" content="arisst.com">
	<meta name="keywords" content="simple blog">
	<meta name="description" content="Aris's News">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Styles -->
	<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
  <%= stylesheet_link_tag    'bootstrap', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'bootstrap-responsive', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'prettyPhoto', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'flexslider', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track' => true %>

	<!-- For IE6-8 -->
	<!--[if lte IE 8]>
	  <%= stylesheet_link_tag 'ie', media: 'all', 'data-turbolinks-track' => true %>
	<![endif]-->

	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- Fav and touch icons -->
	<link rel="shortcut icon" href="<%= asset_path("img/ico/favicon.ico") %>">
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<%= asset_path("img/ico/apple-touch-icon-144-precomposed.png") %>">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<%= asset_path("img/ico/apple-touch-icon-114-precomposed.png") %>">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<%= asset_path("img/ico/apple-touch-icon-72-precomposed.png") %>">
	<link rel="apple-touch-icon-precomposed" href="<%= asset_path("img/ico/apple-touch-icon-57-precomposed.png") %>">

	<style type="text/css">
	.auto-style1 {
		width: 100%;
		zoom: 1;
		text-align: right;
	}
	</style>
</head>
<body>

<%= yield %>

</body>
</html>